# RabbitMQ
# RabbitMQ PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: guoyun-rabbitmq-pv
  namespace: guoyun
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/nfs/rabbitmq
    server: 192.168.10.105

# RabbitMQ PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guoyun-rabbitmq-pvc
  namespace: guoyun
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
  volumeName: guoyun-rabbitmq-pv

# RabbitMQ ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbit-config
  namespace: guoyun
data:
  enabled_plugins: "[rabbitmq_shovel,rabbitmq_shovel_management]."

# RabbitMQ Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: guoyun-rabbitmq
  name: guoyun-rabbitmq
  namespace: guoyun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guoyun-rabbitmq
  template:
    metadata:
      labels:
        app: guoyun-rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-password
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-password
                  key: RABBITMQ_DEFAULT_PASS
            - name: TZ
              value: Asia/Shanghai
          image: rabbitmq:latest
          imagePullPolicy: IfNotPresent
          name: guoyun-rabbitmq
          ports:
            - containerPort: 15672
              name: manager
            - containerPort: 5672
              name: broker
          volumeMounts:
            - mountPath: /etc/rabbitmq/enabled_plugins
              name: rabbitmq-config
              subPath: enabled_plugins
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
      volumes:
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config
            items:
              - key: enabled_plugins
                path: enabled_plugins
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: guoyun-rabbitmq-pvc

---
# RabbitMQ Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: guoyun-rabbitmq
  name: guoyun-rabbitmq
  namespace: guoyun
spec:
  type: NodePort
  ports:
    - name: broker
      port: 5672
      protocol: TCP
      targetPort: 5672
      nodePort: 30672
    - name: manager
      port: 15672
      protocol: TCP
      targetPort: 15672
      nodePort: 31672
  selector:
    app: guoyun-rabbitmq